# Generated by Django 4.2.1 on 2023-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tareas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='observacion',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
