# Generated by Django 4.2.1 on 2023-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tareas_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], max_length=40)),
            ],
        ),
    ]
