# Generated by Django 4.2.1 on 2023-05-25 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_prioridades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.prioridades'),
        ),
    ]
